<?xml version="1.0"?>
<robot name="duckiebot" xmlns:xacro="http://www.ros.org/wiki/xacro">   <!-- xacro'da bu önemli -->  
    <!-- xacro'da başka bir xacro dosyasını include edebiliriz -->
    <xacro:include filename="common_properties.xacro" / >
    <!-- xacro'da parametre tanımlarız -->  
    <!-- robotun gövdesini hard code bi şekilde belirledik ve geri kalan ayarlamaları ona göre yaptık ya, xacroda buna gerek yok--> 
    <xacro:property name="base_length" value="0.34" />
    <xacro:property name="base_width" value="0.15" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.066" />
    <xacro:property name="wheel_length" value="0.05" />




    <link name="base_footprint" >
        <origin xyz= "0 0 0" rpy="0 0 0" />
    </link>

    <!-- xacro'da fonksiyon da tanımlarız, tekerlek linkleri için bi fonksiyon yazalım --> 
    <xacro:macro name="wheel_link" params="prefix"> <!-- linkleri farklı isimlerde tanımlaman lazım, prefix ismiyle parametre olarak geçiririz ismi -->
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy ="${pi / 2.0} 0 0" />  <!-- <urdf hali buydu origin xyz="0 0 0" rpy ="1.57 0 0" /> exact sayıyı yazıyoduk. ${} demek xacronun tanıyacağı bi varaible yazacaksın demektir--> 
                <material name="black" />
            </visual>
        </link>
    </xacro:macro>

    <!-- sağ ve sol tekerlekler için linkler oluşturduk --> 
    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" /> <!-- length width height in meters -->  
            </geometry>
            <origin xyz= "0 0 0.1" rpy="0 0 0" /> 
            <material name="blue" />
        </visual>
    </link>


    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}"/>
            </geometry>
            <origin xyz="0 0 0" rpy ="0 0 0" />
            <material name="grey" />
        </visual>
    </link>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link ="caster_wheel_link" />
        <origin xyz="${base_length / 4.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" /> 
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link ="left_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${base_width / 1.5} 0" rpy="0 0 0" /> 
        <axis xyz="0 -1 0"/> 
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link ="right_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-base_width / 1.5} 0" rpy="0 0 3.14" /> 
        <axis xyz="0 1 0"/> 
    </joint>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link ="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" /> 
    </joint>

</robot>