<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.34" /> <!-- x -->  
    <xacro:property name="base_width" value="0.15" />  <!-- y -->  
    <xacro:property name="base_height" value="0.15" />  <!-- z -->  
    <xacro:property name="wheel_radius" value="0.066" />
    <xacro:property name="wheel_length" value="0.05" />


    <link name="base_footprint" >
        <origin xyz= "0 0 0" rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel_link" params="prefix"> 
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy ="${pi / 2.0} 0 0" />  <!-- <urdf hali buydu origin xyz="0 0 0" rpy ="1.57 0 0" /> exact sayıyı yazıyoduk. ${} demek xacronun tanıyacağı bi varaible yazacaksın demektir--> 
                <material name="black" />
            </visual>
            <!-- colision ekliyoruz, silindir olarak eklmeciez, çünkü tekerlekler  yerle her an temas ediyor ve hareket ediyor, her an collision var, ve silindirin yerle temas eden çok pointi var. Bu durum sistemin yavaşlamasına yol açar ve rvizle gazebo arasında uyumsuzluk görürüsün, gecikmeden dolayı. fakat sphere kullanırsan yerle temas eden sadece bir noktası olur--> 
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy ="0 0 0" /> <!-- silindir gibi rotate etmedik çünkü sphere olduğu için bişi değiştirmicek--> 
            </collision>
            <!-- inertia eklicez common properties'te tanıttığımız fonksiyonu kullanarak, m kilogram cinsinden--> 
            <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}" o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" /> 
        </link>
    </xacro:macro>

 
    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />

    <link name="base_link">
        <visual>
            <geometry>
                 <box size="${base_length} ${base_width} ${base_height}" /> <!-- length width height in meters -->  
                <!--< mesh filename="package://duckiebot_description/meshes/waffle_pi_base.stl" scale="0.001 0.001 0.001"/> -->  
            </geometry>
            <origin xyz= "0 0 ${base_height / 2.0}" rpy="0 0 0" /> 
            <material name="blue" />
        </visual>
        <!-- collision ekliyoruz--> 
        <collision>
            <!-- direkt visual'daki geometriyi ve origini koyduk, basit olması için --> 
            <geometry>
                 <box size="${base_length} ${base_width} ${base_height}" /> 
            </geometry>
            <origin xyz= "0 0 ${base_height / 2.0}" rpy="0 0 0" /> 
        </collision>
        <!-- inertia eklicez common properties'te tanıttığımız fonksiyonu kullanarak--> 
        <xacro:box_inertia m="1.8" x="${base_length}" y="${base_width}" z="${base_height}" o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" /> 
    </link>


    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}"/>
            </geometry>
            <origin xyz="0 0 0" rpy ="0 0 0" />
            <material name="grey" />
        </visual>
        <!-- collisionu direkt yukardan kopyaladık--> 
        <collision>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}"/>
            </geometry>
            <origin xyz="0 0 0" rpy ="0 0 0" />
        </collision>
        <!-- inertia eklicez common properties'te tanıttığımız fonksiyonu kullanarak--> 
        <xacro:sphere_inertia m="0.5" r="${wheel_radius / 2.0}" o_xyz="0 0 0" o_rpy="0 0 0" /> 
    </link>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link ="caster_wheel_link" />
        <origin xyz="${-base_length / 4.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" /> 
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link ="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" /> 
    </joint>
</robot>

